Id:       blockchain-pipes
Version:  0.2

swagger: "2.0"

info:
  description: "Golang pipes demo for HLF blockchain"
  version: "0.2"
  title: "Pipelines tests"


consumes:
  - application/x-www-form-urlencoded
produces:
  - application/json


parameters:

  input_val:
    name: input_val
    in: formData
    description: Input value
    required: true
    type: string
    maxLength: 64

paths:

  /seq/:

    post:
      operationId: runCalcSeq
      summary: Run sequential execution
      parameters:
      - $ref: '#/parameters/input_val'
      responses:
        200:
          description: Key Created
        400:
          description: Parameter Mismatch
        500:
          description: Server Error

  /parallel/:

    post:
      operationId: runCalcParallel
      summary: Run parallel execution
      parameters:
      - $ref: '#/parameters/input_val'
      responses:
        200:
          description: Key Created
        400:
          description: Parameter Mismatch
        500:
          description: Server Error
